version: '3.8'

services:
  db:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: english
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./back-end
    container_name: nest_backend
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 12345
      DATABASE_NAME: english
    volumes:
      - ./back-end:/app
      - transcripts_data:/app/transcripts
      - /app/node_modules  # Tránh xung đột node_modules
    command: ["npm", "run", "start:dev"]

  frontend:
    build: ./front-end
    container_name: react_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    stdin_open: true
    tty: true
    command: ["npm", "start"]
    volumes:
      - ./front-end:/app
      - transcripts_data:/app/public/transcripts
      - /app/node_modules  # Tránh xung đột node_modules

volumes:
  postgres_data:
  transcripts_data:
